[versions]
ktx = "1.10.1"
lifecycle_version = "2.6.1"
activity-compose = "1.7.2"
symbol-processing-api = "1.9.0-1.0.11"

espresso-core = "3.5.1"
androidx-junit = "1.1.5"
junit = "4.13.2"
compose-bom = "2023.06.01"

[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-lifecycle = { module = " androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle_version" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "symbol-processing-api" }

androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-compose-bom = {module = "androidx.compose:compose-bom", version.ref = "compose-bom"}

[plugins]

[bundles]
